#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'proximity-sensor-pubsub==1.0.0','console_scripts','proximity_node'
__requires__ = 'proximity-sensor-pubsub==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('proximity-sensor-pubsub==1.0.0', 'console_scripts', 'proximity_node')()
    )
